name: ta_scanner

channels:
    - default

dependencies:
    - python=3.7
    - click
    - sqlalchemy
    - pandas >= 1.0.0
    - numpy
    - requests
    - pytz
    - matplotlib
    # test resources
    - pytest
    - pip
    - pip:
        - twine
        - ipdb
        - loguru
        - "--editable ."
        - "--editable ../ta_scanner" # this has some overlapping dependencies